### ISSUE TITLE
Two copies of the .appdata.xml file

### ISSUE THREAD

**Issue by AdelKS** [AdelKS/ZeGrapher#16]
Hello!
Hope everything is alright for you @eclipseo, I opened this issue to ask if it's mandatory to have two copies of the file `ZeGrapher.appdata.xml`: one is in the root folder, the other in the `appdata` folder.
Thanks!

**Comment by eclipseo** [comment]
No there should only be one in the /usr/share/metainfo dir.

**Comment by AdelKS** [comment]
Sorry, I am talking about the root of the git folder of ZeGrapher

**Comment by eclipseo** [comment]
There should be only one, the one installed by the build script.

**Comment by eclipseo** [comment]
> Sorry, I am talking about the root of the git folder of ZeGrapher

You can safely remove the one at the root.

**Comment by eclipseo** [comment]
Also I would love if you tagged a new release with the Appdata fixes, the one provided in 3.1.1 is old.

**Comment by AdelKS** [comment]
> You can safely remove the one at the root.

Got it thanks!

> Also I would love if you tagged a new release with the Appdata fixes, the one provided in 3.1.1 is old.

Yea sorry, I will fix that now.

**Comment by eclipseo** [comment]
Thanks a lot!

**Comment by AdelKS** [comment]
And thank you too for your help ! :D

**Comment by AdelKS** [comment]
The appdata files in the master branch are good right ?

**Comment by eclipseo** [comment]
> The appdata files in the master branch are good right ?

yes.

**Comment by AdelKS** [comment]
Thanks! Yea I am seeing that it has the old stuffs in it. Fixed it :D
