### ISSUE TITLE
ZeGrapher plots wrong graphs of simple functions f(x)=a*x

### ISSUE THREAD

**Issue by yurivict** [AdelKS/ZeGrapher#20]
They point wrong direction:

![image](https://user-images.githubusercontent.com/271906/96172731-af809b80-0edb-11eb-800f-5c88480bb7e2.png)

**Comment by AdelKS** [comment]
You are using a development version of ZeGrapher: you shouldn't use "Continuous-build" ones, you can get the latest stable version from the Github releases that are manually written or from https://zegrapher.com

**Comment by yurivict** [comment]
It's hard to tell what does the tag ```continuous``` mean. I interpreted it as "No distinct releases are made, the release process is continuous, any revision should be fine."

**Comment by AdelKS** [comment]
I will change that so it's less confusing :)
