### ISSUE TITLE
Thank you very much for the free open source program!

### ISSUE THREAD

**Issue by s-r-grass** [AdelKS/ZeGrapher#21]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D1%8B/zegrapher-%D0%BF%D0%BE%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2.html).

The project is interesting, so please don't abandon it!

**Comment by AdelKS** [comment]
Hello! Thank you for your kind and encouraging message, I love receiving these, it makes me happy to hear that it is being used and useful :smile: 

It has been 9 years already, I slowly work on it : I am not planning on abandoning it any time soon. I still have lots of things in mind to implement. There will be an update around the end of this year, the beginning of the next one. With log scale and scientific paper quality SVG/PDF export, where one can chose the size of the graph in centimeters, with real size live preview. Compatible with Inkscape for any extra needed tweaks.
