### ISSUE TITLE
Is there a function reference?

### ISSUE THREAD

**Issue by travisfw** [AdelKS/ZeGrapher#22]
The website says "all the usual functions are available" … but what are the usual functions?
I'm trying to chart a cube root, and I tried cbrt(x), and root(x, 3). How can I do this, or, more importantly, how can I see all the functions I can use? Even if it's just a file in the source code, it might be enough for now.

**Comment by AdelKS** [comment]
Hello,

You seem to have been quite frustrated by this to skip common courtesy, cubic root is not available in the current version but you can use "x^(1/3)"

As written on the website, if you read a little further, the "usual" functions are available on a virtual keyboard: you can show it from the window where you enter math expressions. It is true that ZeGrapher lacks of some form of documentation: I will slowly work on it while working on the new version.

**Comment by travisfw** [comment]
Sorry, @AdelKS, what common courtesy did I skip?
Anyhow, thanks for the answer that easily accessible keyboard symbols are supported, and a means for appyling a cube root!

**Comment by AdelKS** [comment]
Hello @travisfw 

> Sorry, @AdelKS, what common courtesy did I skip?

A little "hello" :P

> Anyhow, thanks for the answer that easily accessible keyboard symbols are supported, and a means for appyling a cube root!

You are most welcome! I will add all the additional functions supported by [C++17 and downard](https://en.cppreference.com/w/cpp/header/cmath) actually in a next release.
