### ISSUE TITLE
Graph behaving weirdly when approaching infinity

### ISSUE THREAD

**Issue by TheNeverMan** [AdelKS/ZeGrapher#25]
When function approaches infinity from two sides (e. g. f(x)=1/x) there is a straight line from -Infinity to +Infinity between limits of the function.

**Comment by AdelKS** [comment]
Hello, thanks for the feedback! Yeah I am aware of this problem, I did implement something to not connect infinities like this but it's not bullet proof. Have you tried increasing the curve quality in the settings?

**Comment by TheNeverMan** [comment]
I have tried using newest version on Win. Tried changing curve quality all options from maximum to minimum, also toggling curve smoothing. Nothing worked.

**Comment by TheNeverMan** [comment]
On Linux version 3.0.2 changing curve quality/smoothness does nothing aswell.

**Comment by AdelKS** [comment]
I believe have found the mistake I did in the code, are you able to compile to check ? I can make an AppImage otherwise.

**Comment by AdelKS** [comment]
Actually never mind, I am going on a different plotting algorithm on my latest code, I cannot back port it without significant useless work.

**Comment by AdelKS** [comment]
![image](https://github.com/AdelKS/ZeGrapher/assets/13605217/eadec10d-bb12-4eb8-b8f2-5c25199cac1c)
